name: Run Playwright Tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get public IP and location
        run: |
          response=$(curl -s http://ipinfo.io/json)
          echo "IP and Location Information: $response"

      - name: Check connectivity to specific website
        run: |
          url="https://app.ckbccc.com/"
          response=$(curl -s -o /dev/null -w "%{http_code}" $url)
          if [ "$response" -eq 200 ]; then
            echo "Successfully connected to $url"
          else
            echo "Failed to connect to $url with HTTP status code: $response"
          fi

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Setup Xvfb
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          Xvfb :99 -screen 0 1280x720x24 &
          echo "DISPLAY=:99" >> $GITHUB_ENV

      - name: Install Playwright Chromium
        run: npx playwright install chromium

      - name: Run Playwright tests
        run: npx playwright test

      - name: Upload playwright report and videos
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: reports-and-videos
          path: |
            videos/
            playwright-report/
